from bs4 import BeautifulSoup


def extract_table_rows(
    soup: BeautifulSoup,
    headers: list[str],
    season: str,
) -> list[dict]:
    """
    Extract all player rows from the table body and align them to headers.
    Adds season metadata to each row.

    Note:
    - Data generated by CSS pseudo-elements (e.g., ::after) cannot be retrieved using requests and BeautifulSoup.
      These elements are rendered by the browser and require tools like Selenium to access.
    """

    tbody = soup.find("tbody", class_="row-striping row-hover")

    if not tbody:
        raise ValueError(
            "Table body <tbody class='row-striping row-hover'> not found")

    rows = []
    tr_elements = tbody.find_all("tr", recursive=False)

    for row_idx, tr in enumerate(tr_elements):
        td_elements = tr.find_all("td", recursive=False)

        if len(td_elements) != len(headers):
            continue

        # Extract rank from the first <td> element with specific class
        rank_td = td_elements[0]
        rank_classes = rank_td.get("class", [])
        if isinstance(rank_classes, list) and "column-1" in rank_classes:
            rank = rank_td.get_text(strip=True)
        else:
            rank = None

        values = [td.get_text(strip=True) for td in td_elements]

        row_data = {
            headers[i]: values[i] if i < len(values) else None
            for i in range(len(headers))
        }

        # Add rank explicitly if extracted
        if rank is not None:
            row_data["rank"] = rank

        # add season metadata
        row_data["season"] = season

        rows.append(row_data)

    return rows
